startup-time:
  week-day: 7
  time: "19:30" #format is H:mm
  time-zone: "" # can be null

event-join-cost: 20000
event-breath:
  cost: 1000
  time-mm: 10
breath-damage: 1.5
chests-to-spawn: 99999 #сколько сундуков будет всего заспавнено на арене
world:
  name: "w"
  lobby:
    x: -103
    y: 5
    z: -55
  spawn:
    x: -127
    y: 5
    z: -80

prevent-commands:
  - 123
  - 1324

chest-rarity-list: #доступные редкости для сундуков, используется при генерации
  - rare:1000
  - default:6000
  - extra:9999

event-mobs:
  kill-money: 21.3
