name: RWMoonJourney
version: '${version}'
main: com.reallyworld.rwmoonjourney.RWMoonJourney
api-version: '1.16'
depend:
  - Vault

commands:
  moonjourney:
    aliases:
      - rwmj
      - mj
    usage: /moonjourney <subcommand> [args]

permissions:
  moonjourney.start:
    description: ""
    default: op
  moonjourney.stop:
    description: ""
    default: op
  moonjourney.join:
    description: ""
    default: op
  moonjourney.time:
    description: ""
    default: op
  moonjourney.buybreath:
    description: ""
    default: op
  moonjourney.addchest:
    description: ""
    default: op
  moonjourney.spawnchests:
    description: ""
    default: op
  moonjourney.leave:
    description: ""
    default: op


